<?php
/**
 * Logout Page
 *
 * Handles the termination of the user session. This script performs the following:
 * 1. Verifies the user is currently logged in.
 * 2. Clears all server-side session cookies.
 * 3. Prepares a JavaScript command to ensure client-side cookies are cleared.
 * 4. Destroys the session and redirects the user to the login page via JavaScript.
 */

session_start();

// 1. Security Check
// Verify if the user is logged in. If not, redirect immediately to prevent
// unauthorized access or execution of the logout logic.
if (!isset($_SESSION["username"])) {
    header("Location: login.php");
    exit;
}

// 2. Cookie Cleanup & JavaScript Preparation
// We iterate through all existing cookies to perform two actions:
// - Server-Side: Expire the cookie using setcookie().
// - Client-Side: Build a string to clear cookies via JavaScript in the browser.
$deleteCookie = "";

if (isset($_COOKIE) && is_array($_COOKIE)) {
    foreach ($_COOKIE as $key => $value) {
        // Expire the cookie on the server (set time to past)
        setcookie($key, "", time() - 1 * 60 * 60, "/");

        // Append to the string for client-side clearing
        $deleteCookie .= "$key=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; ";
    }
}

// 3. Clear Session Data
// Remove all session variables from the current execution.
session_unset();

// 4. Destroy Session
// Completely destroy the session storage on the server.
session_destroy();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
</head>
<body>
    <script>
        /**
         * Client-Side Logout Actions
         */

        // 1. Clear client-side cookies using the string generated by PHP
        document.cookie = "<?php echo $deleteCookie; ?>";

        // 2. Provide feedback to the user
        alert("✅ You have been logged out successfully!");

        // 3. Redirect to the login page
        // Using window.location.href ensures the user is sent to the login screen
        // after the alert is acknowledged.
        window.location.href = "login.php";
    </script>
</body>
</html>